import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/document/": [
    {
      text: "电脑端文档",
      icon: "computer",
      prefix: "/document/desktop/",
      collapsable: true,
      children: [
        {
          prefix: "list-songlist/",
          icon: "question",
          text: "常见问题︱列表和外部歌单",
          collapsable: true,
          children: [
            "change-list-position.md",
            "list-multiple-selection.md",
            "list-play-all.md",
            "open-songlist.md",
            "playlist.md",
            "search-play-all",
          ],
        },
        {
          prefix: "lyric/",
          icon: "question",
          text: "常见问题︱桌面歌词",
          collapsable: true,
          children: ["desktop-lyric.md", "velocity-text.md"],
        },
        {
          prefix: "play-download/",
          icon: "question",
          text: "常见问题︱播放与下载",
          collapsable: true,
          children: [
            "cannot-play-download.md",
            "download.md",
            "revise-dns-host.md",
          ],
        },
        {
          prefix: "source/",
          icon: "question",
          text: "常见问题︱自定义源",
          collapsable: true,
          children: ["custom-source.md", "use-source.md"],
        },
        {
          prefix: "sync-backup/",
          icon: "question",
          text: "常见问题︱同步和备份",
          collapsable: true,
          children: ["backup.md", "sync.md"],
        },
        {
          prefix: "update-package/",
          icon: "update",
          text: "常见问题︱软件更新",
          collapsable: true,
          children: ["cannot-update.md", "install-failed.md", "package.md"],
        },
        {
          prefix: "other/",
          icon: "question",
          text: "常见问题︱其他问题",
          collapsable: true,
          children: [
            "antivirus-software.md",
            "cannot-connect-internet.md",
            "headphones-turn-off-unexpectedly.md",
            "interface-abnormal.md",
          ],
        },
        { text: "常见问题︱可用的快捷键", icon: "question", link: "/hotkey" },
        {
          text: "常见问题︱支持的启动参数",
          icon: "question",
          link: "/run-params",
        },
        {
          text: "常见问题︱Scheme URL支持",
          icon: "question",
          link: "/scheme-url",
        },
      ],
    },
    {
      text: "移动端文档",
      icon: "mobile",
      prefix: "/document/mobile/",
      collapsable: true,
      children: [
        {
          prefix: "list-songlist/",
          icon: "question",
          text: "常见问题︱列表和外部歌单",
          collapsable: true,
          children: [
            "list-multiple-selection.md",
            "list-play-all.md",
            "open-songlist.md",
            "playlist.md",
            "songlist-update",
          ],
        },
        {
          prefix: "play-download/",
          icon: "question",
          text: "常见问题︱播放与下载",
          collapsable: true,
          children: ["cannot-play-download.md", "download.md", "revise-dns.md"],
        },
        {
          prefix: "sync-backup/",
          icon: "question",
          text: "常见问题︱同步和备份",
          collapsable: true,
          children: ["backup.md", "sync.md"],
        },
        {
          prefix: "update-package/",
          icon: "update",
          text: "常见问题︱软件更新",
          collapsable: true,
          children: ["cannot-update.md", "install-failed.md", "package.md"],
        },
        {
          prefix: "other/",
          icon: "question",
          text: "常见问题︱其他问题",
          collapsable: true,
          children: ["antivirus-software.md", "desktop-lyric.md"],
        },
        {
          text: "常见问题︱状态栏歌词",
          icon: "question",
          link: "/statusbar-lyric",
        },
      ],
    },
    {
      text: "常见问题︱数据存储路径",
      icon: "folder",
      prefix: "/document/data/",
      collapsable: true,
      children: ["desktop.md", "mobile.md"],
    },
    {
      text: "常见问题︱不支持的功能",
      icon: "restrict",
      prefix: "/document/notsupported/",
      collapsable: true,
      children: ["desktop.md"],
    },
    {
      text: "常见问题︱设置项解析",
      icon: "setting",
      prefix: "/document/notsupsettingported/",
      collapsable: true,
      children: ["desktop.md"],
    },
    {
      text: "软件︱源码的使用方法",
      icon: "generic",
      prefix: "/document/source/",
      collapsable: true,
      children: ["desktop.md", "mobile.md"],
    },
    {
      text: "软件︱许可协议",
      icon: "license",
      prefix: "/document/license/",
      collapsable: true,
      children: ["desktop.md", "mobile.md"],
    },
  ],
});
