import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/document/": [
    {
      text: "电脑端文档",
      icon: "desktop",
      prefix: "/document/desktop/",
      collapsable: true,
      children: [
        {
          prefix: "list-songlist/",
          icon: "songlist",
          text: "常见问题 | 列表和外部歌单",
          collapsable: true,
          children: [
            "change-list-position.md",
            "list-multiple-selection.md",
            "list-play-all.md",
            "open-songlist.md",
            "playlist.md",
            "search-play-all",
          ],
        },
        {
          prefix: "lyric/",
          icon: "question",
          text: "常见问题 | 桌面歌词",
          collapsable: true,
          children: ["desktop-lyric.md", "velocity-text.md"],
        },
        {
          prefix: "play-download/",
          icon: "play",
          text: "常见问题 | 播放与下载",
          collapsable: true,
          children: [
            "cannot-play-download.md",
            "download.md",
            "revise-dns-host.md",
          ],
        },
        {
          prefix: "source/",
          icon: "code",
          text: "常见问题 | 自定义源",
          collapsable: true,
          children: ["custom-source.md", "use-source.md"],
        },
        {
          prefix: "sync-backup/",
          icon: "backup",
          text: "常见问题 | 同步和备份",
          collapsable: true,
          children: ["backup.md", "sync.md"],
        },
        {
          prefix: "update-package/",
          icon: "update",
          text: "常见问题 | 软件更新",
          collapsable: true,
          children: ["cannot-update.md", "install-failed.md", "package.md"],
        },
        {
          prefix: "other/",
          icon: "other",
          text: "常见问题 | 其他问题",
          collapsable: true,
          children: [
            "antivirus-software.md",
            "cannot-connect-internet.md",
            "headphones-turn-off-unexpectedly.md",
            "interface-abnormal.md",
          ],
        },
        { text: "常见问题 | 可用的快捷键", icon: "hotkey", link: "/document/desktop/hotkey/" },
        {
          text: "常见问题 | 支持的启动参数",
          icon: "start",
          link: "/document/desktop/run-params/",
        },
        {
          text: "常见问题 | Scheme URL支持",
          icon: "url",
          link: "/document/desktop/scheme-url/",
        },
      ],
    },
    {
      text: "移动端文档",
      icon: "mobile",
      prefix: "/document/mobile/",
      collapsable: true,
      children: [
        {
          prefix: "list-songlist/",
          icon: "songlist",
          text: "常见问题 | 列表和外部歌单",
          collapsable: true,
          children: [
            "list-multiple-selection.md",
            "list-play-all.md",
            "open-songlist.md",
            "playlist.md",
            "songlist-update",
          ],
        },
        {
          prefix: "play-download/",
          icon: "play",
          text: "常见问题 | 播放与下载",
          collapsable: true,
          children: ["cannot-play.md", "download.md", "revise-dns.md"],
        },
        {
          prefix: "sync-backup/",
          icon: "backup",
          text: "常见问题 | 同步和备份",
          collapsable: true,
          children: ["backup.md", "sync.md"],
        },
        {
          prefix: "update-package/",
          icon: "update",
          text: "常见问题 | 软件更新",
          collapsable: true,
          children: ["cannot-update.md", "install-failed.md", "package.md"],
        },
        {
          prefix: "other/",
          icon: "other",
          text: "常见问题 | 其他问题",
          collapsable: true,
          children: ["antivirus-software.md", "desktop-lyric.md"],
        },
        {
          text: "常见问题 | 状态栏歌词",
          icon: "question",
          link: "/document/mobile/statusbar-lyric/",
        },
      ],
    },
    {
      text: "常见问题 | 数据存储路径",
      icon: "storage",
      prefix: "/document/data/",
      collapsable: true,
      children: ["desktop.md", "mobile.md"],
    },
    {
      text: "常见问题 | 不支持的功能",
      icon: "forbid",
      prefix: "/document/notsupported/",
      collapsable: true,
      children: ["desktop.md"],
    },
    {
      text: "常见问题 | 设置项解析",
      icon: "setting",
      prefix: "/document/setting/",
      collapsable: true,
      children: ["desktop.md"],
    },
    {
      text: "软件 | 源码的使用方法",
      icon: "code",
      prefix: "/document/source/",
      collapsable: true,
      children: ["desktop.md", "mobile.md"],
    },
    {
      text: "软件 | 许可协议",
      icon: "license",
      prefix: "/document/license/",
      collapsable: true,
      children: ["desktop.md", "mobile.md"],
    },
  ],
  "/download/": [
    {
      text: "下载 | 软件下载",
      icon: "download",
      link: "/download/",
      collapsable: true,
    },
    {
      text: "下载 | 安装包说明",
      icon: "package",
      link: "/download/package/",
      collapsable: true,
    },
  ],
  "/github/": [
    {
      text: "Github | 软件",
      icon: "app",
      link: "/github/",
      collapsable: true,
    },
    {
      text: "Github | 文档",
      icon: "docs",
      link: "/github/docs/",
      collapsable: true,
    },
  ],
  "/announcement/": [
    {
      text: "公告 | 全局",
      icon: "announcement",
      link: "/announcement/",
      collapsable: true,
    },
    {
      text: "公告 | 文档",
      icon: "docs",
      link: "/announcement/docs/",
      collapsable: true,
    },
    {
      text: "公告 | 软件",
      icon: "app",
      link: "/announcement/program/",
      collapsable: true,
    },
  ],
});
