name: Deploy Docs

on:
  push:
    branches:
      - dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docs To Server
        run: curl ${{ secrets.SERVER_UPDATE_URL }}
